apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: SelfTest

on:
  workflow_dispatch:
  push:
    branches:
      - "*"

permissions:
  scm-token-own: read
  scm-token-org: read

jobs:
  build:
    if: cloudbees.api.url == 'https://api.saas-preprod.beescloud.com' || cloudbees.api.url == 'https://api.cloudbees.io'
    permissions:
      scm-token-own: read
      id-token: write
    steps:
      - name: Git checkout
        uses: https://github.com/cloudbees-io/checkout@v1

      - name: Run unit tests and verify coding rules
        uses: docker://golang:1.26.0
        run: |
          make verify

      - id: build
        name: Build, scan and push to ECR
        uses: calculi-corp/cb-internal-shared-actions/build@v8
        with:
          go-binary-build: "true"
          go-binary-name: checkout
          kaniko-build: "true"
          run-unit-test: "false"
          registry-url: 020229604682.dkr.ecr.us-east-1.amazonaws.com
          registry-image-name: actions/cloudbees-io-checkout
          registry-type: ECR
          oidc-iam-role: ${{ vars.oidc_staging_iam_role }}

  test-simple-no-repo-specified:
    if: cloudbees.api.url == 'https://api.saas-preprod.beescloud.com'
    needs: build
    steps:
      - name: Run Action
        id: runaction
        uses: ./.cloudbees/testing
        env:
          RUNNER_DEBUG: "1"
      - name: Verify that the repo was checked out
        uses: docker://golang:1.26.0
        run: |
          set -x
          [ -d .git ]
          [ -f Dockerfile ]
          echo Action outputs:
          echo '  Repository URL = ${{ steps.runaction.outputs.repository-url }}'
          echo '  Commit = ${{ steps.runaction.outputs.commit }}'
          echo '  Ref = ${{ steps.runaction.outputs.ref }}'
          [ "${{ steps.runaction.outputs.repository-url }}" = "https://github.com/cloudbees-io/checkout.git" ]
          [ "${{ steps.runaction.outputs.commit }}" = "${{ cloudbees.scm.sha }}" ]
          go build .
  test-simple-origin-repo-specified:
    if: cloudbees.api.url == 'https://api.saas-preprod.beescloud.com'
    needs: build
    steps:
      - name: Run Action
        id: runaction
        uses: ./.cloudbees/testing
        with:
          repository: https://github.com/cloudbees-io/checkout
        env:
          RUNNER_DEBUG: "1"
      - name: Verify that the repo was checked out
        uses: docker://alpine/git:v2.49.1
        run: |
          set -x
          [ -d .git ]
          [ -f Dockerfile ]
          echo Action outputs:
          echo '  Repository URL = ${{ steps.runaction.outputs.repository-url }}'
          echo '  Commit = ${{ steps.runaction.outputs.commit }}'
          echo '  Ref = ${{ steps.runaction.outputs.ref }}'
          [ "${{ steps.runaction.outputs.repository-url }}" = "https://github.com/cloudbees-io/checkout" ]
          [ "${{ steps.runaction.outputs.commit }}" = "${{ cloudbees.scm.sha }}" ]
          [ "`git rev-parse HEAD`" = "${{ cloudbees.scm.sha }}" ]
  test-public-submodule-support:
    if: cloudbees.api.url == 'https://api.saas-preprod.beescloud.com'
    needs: build
    steps:
      - name: Run Action
        uses: ./.cloudbees/testing
        env:
          RUNNER_DEBUG: "1"
        with:
          repository: https://github.com/microsoft/onnxruntime.git
          submodules: recursive
      - name: Verify that the repo was checked out
        uses: docker://alpine:3.22
        run: |
          set -x
          [ -d .git ]
          [ -d cmake/external/emsdk ]
          [ -d include/onnxruntime/core ]
          cat .git/modules/cmake/external/emsdk/config
  test-private-submodule-support:
    if: cloudbees.api.url == 'https://api.saas-preprod.beescloud.com'
    needs: build
    steps:
      - name: Run Action
        uses: ./.cloudbees/testing
        env:
          RUNNER_DEBUG: "1"
        with:
          repository: https://github.com/cloudbees-io/checkout-test.git
          submodules: recursive
      - name: Verify that the repo was checked out
        uses: docker://alpine:3.22
        run: |
          set -x
          [ -d .git ]
          [ -d .git/modules/checkout-test-submodule ]
          [ "$(cat checkout-test-submodule/file-within-submodule)" = 'test content' ]
          cat .git/modules/checkout-test-submodule/config
