apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: SelfTest

on:
  push:
    branches:
      - "*"

jobs:

  build:
    steps:
      - name: Git checkout
        uses: docker://alpine/git:2.43.0
        run: |
          set -x
          git config --global --add safe.directory `pwd`
          git clone ${{ cloudbees.scm.repositoryUrl }} .
          git checkout ${{ cloudbees.scm.sha }}
      - id: test
        name: Run unit tests
        uses: docker://golang:1.21
        run: |
          go test --cover ./...
      - id: dockerconfig
        name: Configure container registry credentials
        uses: cloudbees-io/configure-oci-credentials@v1
        with:
          registry: ${{ vars.STAGING_DOCKER_REGISTRY }}
          username: ${{ secrets.STAGING_DOCKER_USERNAME }}
          password: ${{ secrets.STAGING_DOCKER_PASSWORD }}
      - id: build-image
        name: Build image
        uses: cloudbees-io/kaniko@v1
        with:
          dockerfile: Dockerfile
          destination: ${{ vars.STAGING_DOCKER_REGISTRY }}/staging/cloudbees-io-checkout:${{ cloudbees.scm.sha }}${{ cloudbees.scm.branch == 'main' && format(',{0}/staging/cloudbees-io-checkout:1.0.10,{0}/staging/cloudbees-io-checkout:latest', vars.STAGING_DOCKER_REGISTRY)  || format(',{0}/staging/cloudbees-io-checkout:{1}', vars.STAGING_DOCKER_REGISTRY, cloudbees.version) }}
          labels: maintaner=sdp-pod-3,email=engineering@cloudbees.io
          context: ${{ cloudbees.workspace }}

  test:
    needs: build
    steps:
      - name: Run Action
        uses: ./
      - name: Verify that the repo was checked out
        uses: docker://golang:1.20.5-alpine3.18
        run: |
          set -x
          [ -d .git ]
          [ -f Dockerfile ]
          go build .

